application: velo-nsk
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles
  static_dir: styles
  
- url: /scripts
  static_dir: scripts
  
- url: /.*
  script: velonsk.app
  
libraries:
- name: jinja2
  version: latest
  
builtins:
- remote_api: on